## numpy 모듈
- C언어로 구현된 파이썬 라이브러리로 속도가 빠름

- 고차원으로 구성되어 있는 행렬의 수치연산을 위해 개발됨

- 명령 프롬프트 창에서 pip install numpy로 설치해야 함

In [9]:
import numpy as np

# numpy를 사용하기 위해 array 형태로 만들기
data1 = [1,2,3,4,5]
array1 = np.array(data1)
print(array1)

# array 의 크기와 형태 확인
array1.shape

[1 2 3 4 5]


(5,)

In [10]:
# numpy를 사용하기 위해 array 형태로 만들기
data2 = [1, 2, 3, 4, 5.5]
array2 = np.array(data2)
print(array2) # 정수형 데이터도 실수형으로 바뀌었다.

# array 의 크기와 형태 확인
array2.shape

[1.  2.  3.  4.  5.5]


(5,)

In [11]:
#numpy를 사용하기 위해 array 형태로 만들기
data3 = [1, 2, 3, 4, '새우깡']
array3 = np.array(data3)
print(array3) # 정수형 데이터도 문자열로 바뀌었다.

# array 의 크기와 형태 확인
array3.shape

['1' '2' '3' '4' '새우깡']


(5,)

In [12]:
# array() 함수안에 리스트 바로 사용하기
array4 = np.array([1,2,3,4,5])
print(array4)

[1 2 3 4 5]


In [13]:
# 데이터 타입 확인하기
print('array1:',array1.dtype)
print('array2:',array2.dtype)
print('array3:',array3.dtype)
print('array4:',array4.dtype)

array1: int32
array2: float64
array3: <U11
array4: int32


In [14]:
# 0으로 구성된 N차원 배열 생성 
print(np.zeros((3,4))) #(행의 수, 열의 수)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# 1로 구성된 N차원 배열 생성
print(np.ones((3,4), dtype=np.int16))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
# arange() 함수 - N만큼 연속적으로 차이나는 배열 생성
print(np.arange(10,30,5))

[10 15 20 25]


In [17]:
# linespace() 함수 - N등분하기
x = np.linspace(0, 99, 100) # 0~99까지 100등분
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [18]:
# 2차원의 array 생성하기
array5 = np.array( [ [1,2,3],[3,4,5],[5,6,7] ])
print(array5)

array5.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [19]:
# reshape() 함수를 사용하여 차원을 변경하기
array6=np.arange(12).reshape(4,3)
print(array6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
# reshape() 함수를 사용하여 차원을 변경하기
array7=array6.reshape(2,6)
print(array7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [21]:
# reshape() 함수를 사용하여 차원을 변경하기
array8 = array6.reshape(-1,1)
print(array8)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [22]:
# 참고 : reshape() 함수는 원본 데이터를 복사하여 복사본의 형태를 바꾸고
# resize() 함수는 원본의 데이터를 변경합니다.

In [23]:
# 데이터 합치기 - vstack() / hstack()
array1 = np.array([[1,2],[3,4]])
print(array1)

array2 = np.array([[5,6],[7,8]])
print(array2)
print()
# vstack()
print('-vstack:','\n',np.vstack((array1,array2)))
print()
# hstack()
print('-hstack:','\n',np.hstack((array1,array2)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

-vstack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

-hstack: 
 [[1 2 5 6]
 [3 4 7 8]]


In [24]:
# 2개 이상의 리스트를 array 로 합치기
import numpy as np
name = np.array(['홍길동','일지매','전우치'])
loc = np.array(['서울','부산','대전'])
print(name)
print(loc)
print()

all_data = np.column_stack( (name, loc))
print(all_data)

['홍길동' '일지매' '전우치']
['서울' '부산' '대전']

[['홍길동' '서울']
 ['일지매' '부산']
 ['전우치' '대전']]


In [25]:
# array 산술연산하기
# 예제 데이터 생성하기

array1 = np.array( [ [1,2,3],[4,5,6] ] )
print(array1)

print("\n")

array2 = np.array( [ [10,20,30] , [40,50,60] ])
print(array2)

[[1 2 3]
 [4 5 6]]


[[10 20 30]
 [40 50 60]]


- 데이터 유형이 똑같은 배열은 +,-,*,/ 모두 가능

In [26]:
# array 산술연산
# 1. 덧셈

array1 + array2

array([[11, 22, 33],
       [44, 55, 66]])

In [27]:
# array 산술연산
# 2. 뺄셈

array2 - array1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [28]:
# array 산술연산
# 3. 곱셈

array1 * array2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [29]:
# array 산술연산
# 4. 나눗셈

array2 / array1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [30]:
# 서로 다른 차원의 배열을 묶어서 연산하기- ix_() 함수 사용
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax,bx,cx = np.ix_(a,b,c)
print(ax)
print(bx)

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]


In [31]:
# 서로 다른 차원의 배열을 묶어서 연산하기- ix_() 함수 사용
print(ax + bx)

[[[10]
  [ 7]
  [ 6]]

 [[11]
  [ 8]
  [ 7]]

 [[12]
  [ 9]
  [ 8]]

 [[13]
  [10]
  [ 9]]]


In [32]:
# array 데이터 조회하기
# 1차원 array 조회하기
array1 = np.array([1,2,3,4,5])
print('전체값:' , array1)
print('1번째값:' , array1[0])
print('3번째값:' , array1[2])
print('2-4번째값:' , array1[1:4])

전체값: [1 2 3 4 5]
1번째값: 1
3번째값: 3
2-4번째값: [2 3 4]


In [33]:
# array 데이터 조회하기
# 2차원 array 조회하기
array2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(array2)
print('\n')
print(array2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [34]:
# 예제 데이터 만들기
array1 = np.random.randn(3,3)
array1

array([[-0.09602557,  0.67668049, -1.66174999],
       [-2.78865119,  2.92455237, -0.87973131],
       [ 0.16392176, -0.561678  , -1.24414834]])

In [35]:
# abs() 함수 - 절대값 계산하기
np.abs(array1)

array([[0.09602557, 0.67668049, 1.66174999],
       [2.78865119, 2.92455237, 0.87973131],
       [0.16392176, 0.561678  , 1.24414834]])

In [36]:
# square() 함수 - 제곱값 계산하기
np.square(array1)

array([[0.00922091, 0.45789649, 2.76141304],
       [7.77657544, 8.55300656, 0.77392717],
       [0.02687034, 0.31548217, 1.54790509]])

In [37]:
# ceil() 함수 - 주어진 값보다 큰 가장 가까운 정수 찾기
np.ceil(array1)

array([[-0.,  1., -1.],
       [-2.,  3., -0.],
       [ 1., -0., -1.]])

In [38]:
# floor() 함수 - 주어진 값보다 작은 가장 가까운 정수 찾기
np.floor(array1)

array([[-1.,  0., -2.],
       [-3.,  2., -1.],
       [ 0., -1., -2.]])

In [39]:
# sum() 함수 - 합계 구하기
sum_ex = np.array([1,3,5,7,9])
np.sum(sum_ex)

25

In [40]:
# cumsum() 함수 - 누적합계 구하기
np.cumsum(sum_ex)

array([ 1,  4,  9, 16, 25])

In [41]:
# isnan() 함수 - 주어진 값의 NaN 여부를 찾는 함수(NaN은 잘못된 데이터로, 쓸 수 없는 데이터이다.)

np.isnan(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
# isinf() 함수 - 주어진 값의 무한대(inf) 여부를 찾는 함수
np.isinf(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])